IMAP_URL = 'imaps://imap.gmail.com'
URL = 'smtps://smtp.gmail.com:465'
MAIL_CRED = 'agmailemailaddress@gmail.com:password'
FROM = 'agmailemailaddress@gmail.com'
FENDE = '/home/pi/fende/fende'
PRIVATE_KEY_PATH = 'privatekeypath.pem'
FILES_READ_DIRECTORY = './received_files/'
PUBLIC_KEYS_DIRECTORY = './publicKeys/'
